import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  aboutUsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'about-us',
    },
  ],
  strategySidebar: [
    {
      type: 'autogenerated',
      dirName: 'strategy',
    },
  ],
  operationsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'operations',
    },
  ],
  governanceSidebar: [
    {
      type: 'autogenerated',
      dirName: 'governance',
    },
  ],
  complianceSidebar: [
    {
      type: 'autogenerated',
      dirName: 'compliance',
    },
  ],
  auditsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'audits',
    },
  ],
  engineeringSidebar: [
    {
      type: 'autogenerated',
      dirName: 'engineering',
    },
  ],
  productSidebar: [
    {
      type: 'autogenerated',
      dirName: 'product',
    },
  ],
  registersSidebar: [
    {
      type: 'autogenerated',
      dirName: 'registers',
    },
  ],
};

export default sidebars;

