import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  strategySidebar: [
    {
      type: 'autogenerated',
      dirName: 'strategy',
    },
  ],
  operationsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'operations',
    },
  ],
  governanceSidebar: [
    {
      type: 'autogenerated',
      dirName: 'governance',
    },
  ],
  complianceSidebar: [
    {
      type: 'autogenerated',
      dirName: 'compliance',
    },
  ],
};

export default sidebars;
